### ISSUE TITLE
Fix test data in Breadcrumb, MegaMenu(Nano, MyPART)

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-qa#217]
Fix test data in Breadcrumb, MegaMenu(Nano, MyPART)

Breadcrumb: 
Remove about-nci/organization/dcb/division-of-cancer-biology-test and news-events/press-releases/2019/brca-exchange-test urls as they dont exist in production

Mega Menu:
- Update "title" column for NANO and MyPART as per Prod
- Remove 'pediatric-adult-rare-tumor/espanol' as it does not exist on Prod
- Remove 'nano/espanol/cancer/sobrellevar/sentimientos' as it does not exist on Prod
- Remove 'about-cancer/coping/feelings/relaxation/hpv-vaccine-presidents-cancer-panel-improving-uptake' as it does not exist on Prod
- Remove 'about-cancer/coping/feelings/relaxation/vitamin-d-supplement-cancer-prevention' as it does not exist on Prod

**Comment by blairlearn** [comment]
@SupriyaSaxena0605 - Please provide more detail.  What specific test data are you fixing and why?

The data on the test sites does should not be changing, so why do the tests need to change?

**Comment by SupriyaSaxena0605** [comment]
@blairlearn I have added details and reason for the change. Please update if these should not change.

**Comment by blairlearn** [comment]
The content for testing (generally known as "the default content") exercises all of the platform's _functionality_, but that's the extent of it. (This is why we don't run the automated regression tests against www.cancer.gov.) The content on the environments where automation is run is not intended to mirror production and will never be updated to match production.

The only reasons for modifying the test data are:

* Adding new tests.
* Functionality has changed.
* The content for testing has changed.

The purpose of this issue is to modify test data because the content it tests does not exist on production.  As long as the test content exists on the testing environments (e.g. www-dev-ac, www-int-ac, and the various ODEs) there is no need to edit/remove/change the tests.
